### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by angelosuinan** [angelosuinan/recipe#1]
##  📋 Todo:

- [ ] Fix Mocking of resolver in test
- [x] Add readme
- [ ] Complete Graphql Tests
- [ ] Enhance error message user
- [ ] Include Client and server to Docker
- [ ] handle loading state
- [ ] Replace the bare `user_id` with JWT token
- [ ] AWS S3 integration (3rd party API integration)
- [ ] Paginated queries
